Admin/Controllers/TeacherController.cs
using Admin.Common.HelperClass;
using Admin.Contract.DBObjects;
using Admin.Contract.Interface.Implementation;
using Admin.Contract.Model.Master;
using Admin.Contract.Model.Student;
using Admin.Contract.Model.Teacher;
using Admin.Contract.Models.HttpRequestResponse;
using Dapper;
using Microsoft.AspNetCore.Mvc;
using System.Net;

namespace Admin.Web.Controllers
{
    public class TeacherController : Controller
    {
        private readonly IUserRepositry _userDataService;

        public TeacherController(IUserRepositry userDataService)
        {
            _userDataService = userDataService;
        }
        public async Task<IActionResult> TeacherList()
        {

            var query = SqlQry.GetTeacherDetails;
            IEnumerable<TeacherDetails> result = await _userDataService.ExcuteQuaryAsync<TeacherDetails>(query, null);
            return View(result);

        }
        [HttpGet]
        public async Task<IActionResult> Addteacher()
        {
            var query = StoredProcedures.GETTYPEMASTER;
            var parameters = new DynamicParameters();
            parameters.Add("@Type", "Gender");
            IEnumerable<TypeMaster> typemaster = await _userDataService.ExcuteSPAsync<TypeMaster>(query, parameters);
            var GendertList = SelectListHelper.ConvertToSelectList(typemaster, m => m.Type_Code.ToString(), m => m.Type_Name);
            ViewBag.Gender = GendertList;

            var query1 = SqlQry.GetBloodGroopDD;
            IEnumerable<TypeMaster> result = await _userDataService.ExcuteQuaryAsync<TypeMaster>(query1, null);
            var BloodGroup = SelectListHelper.ConvertToSelectList(result, m => m.Type_Code.ToString(), m => m.Type_Name);
            ViewBag.BloodGroup = BloodGroup;

            var query2 = SqlQry.GetClassDD;
            IEnumerable<TypeMaster> result1 = await _userDataService.ExcuteQuaryAsync<TypeMaster>(query2, null);
            var classes = SelectListHelper.ConvertToSelectList(result1, m => m.Type_Code.ToString(), m => m.Type_Name);
            ViewBag.classes = classes;

            var query3 = SqlQry.GetSectionDD;
            IEnumerable<TypeMaster> result3 = await _userDataService.ExcuteQuaryAsync<TypeMaster>(query3, null);
            var Section = SelectListHelper.ConvertToSelectList(result3, m => m.Type_Code.ToString(), m => m.Type_Name);
            ViewBag.Section = Section;

            var query4 = StoredProcedures.GETCITYDD;
            var parameters3 = new DynamicParameters();
            parameters3.Add("@Type", "State");
            IEnumerable<TypeMaster> typemaster3 = await _userDataService.ExcuteSPAsync<TypeMaster>(query4, parameters3);
            var StateList = SelectListHelper.ConvertToSelectList(typemaster3, m => m.Type_Code.ToString(), m => m.Type_Name);
            ViewBag.State = StateList;

            var parameters4 = new DynamicParameters();
            parameters4.Add("@Type", "Country");
            IEnumerable<TypeMaster> typemaster4 = await _userDataService.ExcuteSPAsync<TypeMaster>(query4, parameters4);
            var CountryList = SelectListHelper.ConvertToSelectList(typemaster4, m => m.Type_Code.ToString(), m => m.Type_Name);
            ViewBag.Country = CountryList;
            return View();
        }
        [HttpPost]
        public async Task<JsonResult> AddteacherDetails([FromForm] TeacherDetails td)
        {
            string msg = "";
            if (!ModelState.IsValid)
            {
                try
                {
                    var query = StoredProcedures.INSERTUPDATE_TEACHERDETAILS;
                    var parameters = new DynamicParameters();
                    parameters.Add("@TeacherId", td.TeacherId);
                    parameters.Add("@TeacherFName", td.TeacherFName);
                    parameters.Add("@TeacherLName", td.TeacherLName);
                    parameters.Add("@DOB", td.DOB);
                    parameters.Add("@JoiningDate", td.JoiningDate);
                    parameters.Add("@Gender", td.Gender);
                    parameters.Add("@SubjectTaught", td.SubjectTaught);
                    parameters.Add("@Department", td.Department);
                    parameters.Add("@Qualification", td.Qualification);
                    parameters.Add("@Salary", td.Salary);
                    parameters.Add("@TeacherEmail", td.TeacherEmail);
                    parameters.Add("@TeacherPhone", td.TeacherPhone);
                    parameters.Add("@Address1", td.Address1);
                    parameters.Add("@Address2", td.Address2);
                    parameters.Add("@City", td.City);
                    parameters.Add("@State", td.State);
                    parameters.Add("@Country", td.Country);
                    parameters.Add("@PostalCode", td.PostalCode);
                    parameters.Add("@FathersName", td.FathersName);
                    parameters.Add("@MothersName", td.MothersName);
                    parameters.Add("@EmergencyContact", td.EmergencyContact);
                    parameters.Add("@Natinality", "1");
                    parameters.Add("@TeacherBloodGroup", td.TeacherBloodGroup);
                    parameters.Add("@MedicalHistory", td.MedicalHistory);
                    parameters.Add("@Imageupload", td.Imageupload);


                    var result = await _userDataService.ExcuteSPAsync<StudentDetails>(query, parameters);
                    msg = "Success";
                }
                catch (Exception ex)
                {
                    msg = ex.Message;
                }
                return Json(msg);
            }
            return Json(msg);
        }

        [HttpPost]
        public async Task<JsonResult> GetTeacherName(string Teacher_Code)
        {
            var query = StoredProcedures.GETTEACHERDD;
            var parameters = new DynamicParameters();
            parameters.Add("@Teacher_Code", Teacher_Code);
            IEnumerable<TypeMaster> typemaster = await _userDataService.ExcuteSPAsync<TypeMaster>(query, parameters);
            var EmpList = SelectListHelper.ConvertToSelectList(typemaster, m => m.Type_Code.ToString(), m => m.Type_Name);
            return Json(EmpList);
        }


        [HttpPost]
        public async Task<JsonResult> GetTeachdetails(string TeacherId)
        {
            var query = StoredProcedures.GET_TEACHER_DETAILS;
            var parameters = new DynamicParameters();
            parameters.Add("@TeacherId", TeacherId);
            var employees = await _userDataService.SingleModelSPAsync<TeacherDetails>(query, parameters);
            return Json(new ResponseDataEnvelop<TeacherDetails>
            {
                StatusCode = HttpStatusCode.OK,
                Data = employees
            });
        }
    }
}

Admin/Views/Teacher/TeacherList.cshtml
@{
    Layout = "_Layout";
}

@model IEnumerable<Admin.Contract.Model.Teacher.TeacherDetails>
<div class="d-md-flex d-block align-items-center justify-content-between my-4 page-header-breadcrumb">
    <h1 class="page-title fw-semibold fs-18 mb-0">Students List</h1>
    <div class="ms-md-1 ms-0">
        <nav>
            <ol class="breadcrumb mb-0">
                <li class="breadcrumb-item"><a href="javascript:void(0);">Teachers</a></li>
                <li class="breadcrumb-item active" aria-current="page">Teachers List</li>
            </ol>
        </nav>
    </div>
</div>


<div class="row">
    <div class="col-xl-12">
        <div class="card custom-card">
            <div class="card-header justify-content-between">
                <a asp-area="" asp-controller="Teacher" asp-action="Addteacher" class="btn btn-primary label-btn">
                    <i class="ri-user-add-line label-btn-icon me-2"></i>
                    Add Teacher
                </a>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table text-nowrap" id="myTable">
                        <thead>
                            <tr>
                                <th scope="col">Name</th>
                                <th scope="col">Created On</th>
                                <th scope="col">Number</th>
                                <th scope="col">Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    @if (item.Gender == "1")
                                    {
                                        <td scope="row">
                                            <div class="d-flex align-items-center">
                                                <span class="avatar avatar-xs me-2 online avatar-rounded">
                                                    <img src="../../assets/images/faces/15.jpg" alt="img">
                                                </span>@(item.TeacherFName +" "+item.TeacherLName)
                                            </div>
                                        </td>
                                    }
                                    else if (item.Gender == "2")
                                    {
                                        <td scope="row">
                                            <div class="d-flex align-items-center">
                                                <span class="avatar avatar-xs me-2 offline avatar-rounded">
                                                    <img src="../../assets/images/faces/6.jpg" alt="img">
                                                </span>@(item.TeacherFName + " " + item.TeacherLName)
                                            </div>
                                        </td>
                                    }
                                    else
                                    {
                                        <td scope="row">
                                        </td>
                                    }

                                    @*  <th scope="row">@item.StudentName</th> *@
                                    <td>@item.CreatedDate</td>
                                    <td>@item.TeacherPhone</td>
                                    <td><span class="badge bg-success-transparent">Active</span></td>
                                </tr>
                            }
                          
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>
   
</div>
<script>

    $(document).ready(function () {
        $('#myTable').DataTable();
       
    });

</script>