Admin/Areas/Master/Controllers/FormMasterController.cs
using Admin.Contract.Interface.Implementation;
using Admin.Contract.Interface.Infrastructure;
using Admin.Contract.Model.Master;
using Dapper;
using DocumentFormat.OpenXml.Spreadsheet;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System.Globalization;
using System.Text.Json;

namespace Admin.Web.Areas.Master.Controllers
{
    [Area("Master")]
    [Route("Master/[controller]/[action]")]
    [Authorize(Roles = "Admin")]
    public class FormMasterController : Controller
    {
        private readonly IConnectionFactory _connectionFactory;
        private readonly IUserRepositry _userDataService;
        public FormMasterController(IUserRepositry userDataService, IConnectionFactory connectionFactory)
        {
            _userDataService = userDataService;
            _connectionFactory = connectionFactory;
        }

        public async Task<IActionResult> Index()
        {
            var model = new List<TableMasterModel>();
            using (var conn = _connectionFactory.GetConnection)
            {
                conn.Open();
                var query = "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' ORDER BY TABLE_NAME ASC ";
                model = (await conn.QueryAsync<TableMasterModel>(query, null)).ToList();
            }
            return View(model);
        }
        public IActionResult MyForm(string TblName)
        {
            ViewBag.TblName = TblName;
            // Replace with your actual table name
            var columns = GetTableColumns(TblName);
            return View(columns);
        }

        public IActionResult SaveData1([FromBody] JsonElement formData, string TblName)
        {
            using (var conn = _connectionFactory.GetConnection)
            {
                conn.Open();
                // Build the SQL query to insert data into the CITYMAST table
                //var columns = formData.EnumerateObject().Select(p => p.Name);

                var columns = formData.EnumerateObject()
                          .Where(p => p.Value.ValueKind != JsonValueKind.Null && !p.Value.ToString().Equals(""))
                          .Select(p => p.Name);

                var values = string.Join(", ", columns.Select(name => "@" + name));
                var query = $"INSERT INTO {TblName} ({string.Join(", ", columns)}) VALUES ({values})";

                // Create a dynamic parameter object with parameter names matching the column names
                var parameters = new DynamicParameters();
                foreach (var property in formData.EnumerateObject().Where(p => p.Value.ValueKind != JsonValueKind.Null && !p.Value.ToString().Equals("")))
                {
                    // Convert JsonElement values to appropriate types
                    object value;
                    switch (property.Value.ValueKind)
                    {
                        case JsonValueKind.String:
                            if (property.Name.ToLower().Contains("date"))
                            {
                                // Specify the expected date format for parsing
                                string[] formats = { "yyyy-MM-dd", "M/d/yyyy", "MM/dd/yyyy", "yyyy-MM-ddTHH:mm:ss.fff" }; // Add your specific formats here
                                if (DateTime.TryParseExact(property.Value.GetString(), formats, CultureInfo.InvariantCulture, DateTimeStyles.None, out DateTime parsedDate))
                                {
                                    value = parsedDate;
                                }
                                else
                                {

                                    throw new FormatException($"Invalid date format for {property.Name}");
                                }
                            }
                            else
                            {
                                value = property.Value.GetString();
                            }
                            break;                          

                        case JsonValueKind.Number:
                            value = property.Value.GetInt32(); // Adjust this based on the actual type of the column
                            break;
                        case JsonValueKind.True:
                        case JsonValueKind.False:
                            value = property.Value.GetBoolean();
                            break;
                        case JsonValueKind.Null:
                            value = DBNull.Value;
                            break;
                        default:
                            throw new NotSupportedException($"Unsupported JSON value kind: {property.Value.ValueKind}");
                    }

                    parameters.Add("@" + property.Name, value);
                }

                // Execute the query with the dynamic parameters
                conn.Execute(query, parameters);
            }

            return Ok(new { success = true });
        }


        public IActionResult SaveData([FromBody] JsonElement formData, string TblName)
        {
            using (var conn = _connectionFactory.GetConnection)
            {
                conn.Open();
                // Build the SQL query to insert data into the CITYMAST table
                //var columns = formData.EnumerateObject().Select(p => p.Name);

                var columns = formData.EnumerateObject()
                          .Where(p => p.Value.ValueKind != JsonValueKind.Null && !p.Value.ToString().Equals(""))
                          .Select(p => p.Name);

                var values = string.Join(", ", columns.Select(name => "@" + name));
                var query = $"INSERT INTO {TblName} ({string.Join(", ", columns)}) VALUES ({values})";

                // Create a dynamic parameter object with parameter names matching the column names
                var parameters = new DynamicParameters();
                foreach (var columnName in columns)
                {
                    // Convert JsonElement values to appropriate types
                    object value;
                    var property = formData.GetProperty(columnName);
                    switch (property.ValueKind)
                    {
                        case JsonValueKind.String when columnName.ToLower().Contains("date"):
                            string[] formats = { "yyyy-MM-dd", "M/d/yyyy", "MM/dd/yyyy", "yyyy-MM-ddTHH:mm:ss.fff" };
                            if (DateTime.TryParseExact(property.GetString(), formats, CultureInfo.InvariantCulture, DateTimeStyles.None, out DateTime parsedDate))
                            {
                                value = parsedDate;
                            }
                            else
                            {
                                throw new FormatException($"Invalid date format for {columnName}");
                            }
                            break;

                        case JsonValueKind.String:
                            value = property.GetString();
                            break;

                        case JsonValueKind.Number:
                            value = property.GetInt32(); // Adjust this based on the actual type of the column
                            break;
                        case JsonValueKind.True:
                        case JsonValueKind.False:
                            value = property.GetBoolean();
                            break;
                        case JsonValueKind.Null:
                            value = DBNull.Value;
                            break;
                        default:
                            throw new NotSupportedException($"Unsupported JSON value kind: {property.ValueKind}");
                    }

                    parameters.Add("@" + columnName, value);
                }

                // Execute the query with the dynamic parameters
                conn.Execute(query, parameters);
            }

            return Ok(new { success = true });
        }
        private List<FormMasterModel> GetTableColumns(string tableName)
        {
            using (var conn = _connectionFactory.GetConnection)
            {
                string query = "SELECT COLUMN_NAME AS ColumnName, DATA_TYPE AS DataType,CHARACTER_MAXIMUM_LENGTH ,IS_NULLABLE as IS_NULLABLE,COLUMNPROPERTY(OBJECT_ID(TABLE_SCHEMA + '.' + TABLE_NAME), COLUMN_NAME, 'IsIdentity') IsIdentity FROM INFORMATION_SCHEMA.COLUMNS WHERE  TABLE_NAME = @TableName";
                conn.Open();
                var columns = conn.Query<FormMasterModel>(
                  query, new { TableName = tableName }
                ).ToList();


                //var columns = conn.Query<FormMasterModel>(
                //    "SELECT COLUMN_NAME AS ColumnName, DATA_TYPE AS DataType,CHARACTER_MAXIMUM_LENGTH ,IS_NULLABLE as IS_NULLABLE " +
                //    "FROM INFORMATION_SCHEMA.COLUMNS " +
                //    "WHERE  COLUMNPROPERTY(OBJECT_ID(TABLE_SCHEMA + '.' + TABLE_NAME), COLUMN_NAME, 'IsIdentity') = 0 AND TABLE_NAME = @TableName",
                //    new { TableName = tableName }
                //).ToList();

                return columns;
            }
        }


        [HttpPost]
        public IActionResult GetTabledata(string tableName)
        {
            var data = GetAllData(tableName);
            return Json(data);
        }


        private IEnumerable<dynamic> GetAllData(string tableName)
        {
            using (var conn = _connectionFactory.GetConnection)
            {
                conn.Open();
                var sql = $"SELECT * FROM {tableName}";
                var data = conn.Query(sql);
                return data;
            }
        }


        public IActionResult UpdateData([FromBody] JsonElement formData, string TblName)
        {
            using (var conn = _connectionFactory.GetConnection)

Admin/Controllers/AttendenceController.cs
using Admin.Common.HelperClass;
using Admin.Contract.DBObjects;
using Admin.Contract.Interface.Implementation;
using Admin.Contract.Model.Attendence;
using Admin.Contract.Model.Master;
using Admin.Contract.Model.Student;
using Admin.Contract.Models.HttpRequestResponse;
using Dapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Net;

namespace Admin.Web.Controllers
{
    public class AttendenceController : Controller
    {
        private readonly IUserRepositry _userDataService;

        public AttendenceController(IUserRepositry userDataService)
        {
            _userDataService = userDataService;
        }
        public async Task<IActionResult> Index()
        {
            var query = StoredProcedures.ManageStudentAttendenceLog;
            var parameters = new DynamicParameters();
            parameters.Add("@Action", "ALL");
            IEnumerable<StudentAttendenceLog> result = await _userDataService.ExcuteQuaryAsync<StudentAttendenceLog>(query, parameters);
            return View(result);
        }
        public async Task<IActionResult> GetAllAttendence()
        {
            var query = StoredProcedures.ManageStudentAttendenceLog;
            var parameters = new DynamicParameters();
            parameters.Add("@Action", "ALL");
            var results = await _userDataService.ExcuteQuaryAsync<StudentAttendenceLog>(query, parameters);

            var events = new List<object>();
            foreach (var result in results)
            {
                events.Add(new
                {
                    id = result.Id, // Assuming Id is the property for the id
                    start = result.AtDate,
                    end = result.AtDate,
                    title = result.StudentName,
                    backgroundColor = "#f5b849",
                    //borderColor = result.BorderColor,
                    borderColor = "#f5b849",
                    description = result.LeaveType,
                });
            }

            return Json(events);
        }

        public async Task<IActionResult> AddAttendence()
        {
            var query2 = SqlQry.GetClassDD;
            IEnumerable<TypeMaster> result1 = await _userDataService.ExcuteQuaryAsync<TypeMaster>(query2, null);
            var classes = SelectListHelper.ConvertToSelectList(result1, m => m.Type_Code.ToString(), m => m.Type_Name);
            ViewBag.classes = classes;

            var query3 = SqlQry.GetSectionDD;
            IEnumerable<TypeMaster> result3 = await _userDataService.ExcuteQuaryAsync<TypeMaster>(query3, null);
            var Section = SelectListHelper.ConvertToSelectList(result3, m => m.Type_Code.ToString(), m => m.Type_Name);
            ViewBag.Section = Section;


            return View();
        }
        [HttpGet]
        public async Task<JsonResult> StudentList( string ClassId, string SectionId)
        {
            string query = "";
            try
            {
                if (SectionId == null || SectionId == "") {
                    query = "select StudentId,StudentName,s.ClassId,cm.ClassName,s.SectionId,sm.SectionNames from StudentDetails s inner join ClassMast cm on s.ClassId= cm.ClassId inner join SectionMast sm on s.SectionId = sm.SectionId where cm.ClassId='" + ClassId + "'  and s.IsActive='1'";
                }
                else
                {
                    query = "select StudentId,StudentName,s.ClassId,cm.ClassName,s.SectionId,sm.SectionName from StudentDetails s inner join ClassMast cm on s.ClassId= cm.ClassId inner join SectionMast sm on s.SectionId = sm.SectionId where cm.ClassId='" + ClassId + "' and sm.SectionId='" + SectionId + "' and s.IsActive='1'";
                }
                // query = SqlQry.StudentList;
                IEnumerable<StudentAttendenceLog> result = await _userDataService.ExcuteQuaryAsync<StudentAttendenceLog>(query, null);
                return Json(new ResponseDataEnvelop<IEnumerable<StudentAttendenceLog>>
                {
                    StatusCode = HttpStatusCode.OK,
                    Data = result
                });
            }
            catch (Exception ex)
            {
                return Json(new ReponseMessageEnvelop
                {
                    StatusCode = HttpStatusCode.InternalServerError,
                    ErrorMessage = ex.Message
                });
            }
        }
    }
}

Admin/Views/Attendence/AddAttendence.cshtml
@{
    ViewBag.Title = "AddAttendence";
}
@model Admin.Contract.Model.Student.StudentDetails

<div class="container-fluid">

    <!-- Page Header -->
    <div class="d-md-flex d-block align-items-center justify-content-between my-4 page-header-breadcrumb">
        <h1 class="page-title fw-semibold fs-18 mb-0">Attendence</h1>
        <div class="ms-md-1 ms-0">
            <nav>
                <ol class="breadcrumb mb-0">
                    <li class="breadcrumb-item"><a href="javascript:void(0);">Studence</a></li>
                    <li class="breadcrumb-item"><a href="javascript:void(0);">Attendence</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Add</li>
                </ol>
            </nav>
        </div>
    </div>

    <div class="row">
        <div class="col-xl-12">
            <div class="card custom-card">
                <div class="card-header">
                    <div class="card-title">Add Attendence</div>
                </div>
                <div class="card-body">
                    <div class="form-group row">
                        <div class="col-md-6 mb-3">
                            <label class="form-label">Class <span style="color:red">*</span></label>

                            @{
                                SelectList Class = new SelectList(ViewBag.classes, "Value", "Text");
                            }
                            @Html.DropDownListFor(m => m.ClassId, Class as SelectList, "Select Class", new { @class = "form-control", @title = "Class", @tabindex = "21" })
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="Class" class="form-label">Section </label>

                            @{
                                SelectList Section = new SelectList(ViewBag.Section, "Value", "Text");
                            }
                            @Html.DropDownListFor(m => m.SectionId, Section as SelectList, "Select Section", new { @class = "form-control", @title = "Section", @tabindex = "21" })
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-3">
                    </div>
                    <div class="col-md-12 grid-margin stretch-card">
                        <div class="card">
                            <div class="card-body">
                                <table class="table table-bordered table-responsive table-condensed" id="tblAttenedence" style="width:100%">
                                </table>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        getData();
    })

    function getData() {
       // url= '@Url.Action("Deletedata", "FormMaster", new { area = "Master" })' + '?TblName=' + TableId,
        var response = Get('/Attendence/StudentList');
        if (ValidateResponse(response)) {
            console.log(response);
            debugger;
            dtMainCamera.clear();
            dtMainCamera.rows.add(response.data);
            dtMainCamera.draw();
        }
    }
    var dtMainCamera = {};
    dtMainCamera = $('#tblAttenedence').DataTable({
        data: [],
        responsive: true,
        dom: 'Bfrtip',
        scroller: true,
        searching: true,
        scrollY: "400px",
        scrollX: true,
        fixedColumns: true,
        scrollCollapse: true,
        columns: [

            //{ data: 'brandId', title: 'Brand Id', className: 'reorder' },
            { data: 'id', title: 'Id' },
            { data: 'countryName', title: 'Country Name' },
            {
                title: 'Country',
                "mRender": function (data, type, row) {
                    var row2 = "<input  type='textbox' id='" + row.Id + "' value='" + row.countryName + "' class='text'/>";
                    return row2
                }, "aTargets": [1]
            },
        ],
        pageLength: 10,
        order: [],
        columnDefs: [{ className: 'dt-center', targets: '_all' }, { orderable: true, searchable: true, targets: [1, -1] }],
        buttons: [
            {
                extend: 'excel',
                exportOptions: {
                    format: {
                        body: function (inner, rowidx, colidx, node) {
                            if ($(node).children("input").length > 0) {
                                return $(node).children("input").first().val();
                            } else {
                                return inner;
                            }
                        }
                    }
                }
            }
        ]
    });



    </script>